export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ADD_USER = "ADD_USER";
export const ADD_HIDDEN_GEM = "ADD_HIDDEN_GEM";
export const ADD_FOOD_TRUCK = "ADD_FOOD_TRUCK";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const ADD_THOUGHT = "ADD_THOUGHT";
