// export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

// export const ADD_TO_CART = "ADD_TO_CART";
// export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const CLEAR_CART = "CLEAR_CART";
// export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
// export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ADD_USER = "ADD_USER";
export const ADD_HIDDEN_GEM = "ADD_HIDDEN_GEM";
export const ADD_FOOD_TRUCK = "ADD_FOOD_TRUCK";
export const ADD_RESTAURANT = "ADD_RESTAURANT";